//  arthematic operater//
let a = 2
let b = 3
console.log(a+b); ///addition.
console.log(a-b); ///subtraction.
console.log(a*b); ///multiplication.
console.log(a/b); ///dividation.

console.log("-------------------------------------------------------");

// string operators
let c="str+"
let d="+ing"
console.log(c+d);

console.log("-------------------------------------------------------");

let e = 3;
let g = "1"
console.log(e + g); //Explicit operrators
console.log(+e + +g); //Explicit operrators


console.log("-------------------------------------------------------");

//comaparision operators
console.log(a < b); //is less than
console.log(a > b); // is greater than
console.log(a == b) // is equal to 
console.log(a != b) // is not equal to

console.log("----------------------------------------------------");

//Type Secure
a = "3";
b = "4";

console.log(a === b); //type check than equal to
console.log(a !== b);  //type check then nor equal to

console.log("-------------------------------------------------------");

let str = "4";
let str2 = 4;
console.log(str === str2); //type check than equal to

console.log("-------------------------------------------------------");

//And | Or operators

console.log( a < b && a > b); //And operator
console.log(a < b || a > b);  // Or operator

